### ISSUE TITLE
Exwm 0.8 can't work well with switch-window

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#180]
When I update to exwm,  switch-window package can't work again, I can't find the reason, any suggestion?

**Comment by tumashu** [comment]
Now, I can't find this change: https://github.com/ch11ng/exwm/commit/4838f2b7fa2a8f3bdd2a8b2f779039a1b397e12b

**Comment by ch11ng** [comment]
I'll look into this issue a little later.

**Comment by ch11ng** [comment]
Fixed in 0d00a92fad1f70131c35c4e90e57ef9d3e2f0ab4.

**Comment by tumashu** [comment]
I still can't use switch-window with exwm, I don't know the reason.

**Comment by ch11ng** [comment]
How do you set it up?

**Comment by tumashu** [comment]
There is no special setup for switch-window package, the below is my .xsesson file
```
if [ -f ~/.bashrc ]; then
source ~/.bashrc
fi

# exec ~/project/stumpwm/stumpwm
# exec sawfish
# exec gnome-screensaver &
# exec sawfish-xfce-session

# Emacs X input method (exim) setting
# export XMODIFIERS=@im=exim
# export GTK_IM_MODULE=xim
# export QT_IM_MODULE=xim
# export CLUTTER_IM_MODULE=xim

# xmodmap -e 'keycode 135 = Super_R' &
export exwm_x_enable="yes"

xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
    -remove _NET_DESKTOP_NAMES \
    -remove _NET_CURRENT_DESKTOP 2> /dev/null

xhost +
# exec dbus-launch --exit-with-session emacs &
exec dbus-launch --exit-with-session emacs
# sleep 0.3

# exec startxfce4 $@

```

**Comment by tumashu** [comment]
https://github.com/tumashu/exwm-x/blob/master/exwm-x-example.el  is my exwm config

**Comment by ch11ng** [comment]
Please try debug `exwm-input--on-FocusIn`.

**Comment by tumashu** [comment]
我测试了一下，when 里面的命令没有执行，其中 (slot-value obj 'detail) = 4 , xcb:NotifyDetail:Inferior=2 原因未知，这个会不会和 #177 有关系？

**Comment by ch11ng** [comment]
I see.  I'll add that condition.

**Comment by tumashu** [comment]
It works, thanks very much, if possible, suggest add a FAQ to record this kind problem.
