### ISSUE TITLE
Frame `#<frame emacs-25.1@..> is on a different DISPLAY (":0.0" instead of ":0")

### ISSUE THREAD

**Issue by avoine** [ch11ng/exwm#213]
I think there is a conflict between (frame-parameter nil 'display) and (slot-value exwm--connection 'display)
because exwm won't start unless I set the DISPLAY shell variable to ":0" instead of the default ":0.0".

I was not sure if that bug belong to xelb or exwm.

**Comment by ch11ng** [comment]
What's the results of these two forms? And what's the name of the socket file (in `/tmp/.X11-unix/`) when `$DISPLAY` is `:0.0`? XELB understands `:0.0` and `:0` are equivalent and will connect to `/tmp/.X11-unix/X0` no matter which value is set.

BTW why `$DISPLAY` is set to `:0.0`?

**Comment by tumashu** [comment]
When I package exwm for guixsd, I have the same problem  and exwm can't work. the debug message
is like this:

```
[EXWM] Frame \342\200\230#<frame emacs-25.1@tumashu 0x8e7c650>\342\200\231 is o$
[EXWM] Frame \342\200\230#<frame *scratch* 0x884ae70>\342\200\231 is on a diffe$
[EXWM] Frame \342\200\230#<frame *scratch* 0x12f50e70>\342\200\231 is on a diff$
[EXWM] Frame \342\200\230#<frame *scratch* 0x12e9c820>\342\200\231 is on a diff$
user-error: [EXWM] Workspace index out of range: 0

```

**Comment by avoine** [comment]
I was on guixsd too.

**Comment by ch11ng** [comment]
d4cfa564be680cec3fe1372e3bc9b29834e0d98a should fix that.

**Comment by spacefrogg** [comment]
The commit does not fix the problem. (Using it from a fresh nixos install.) The problem is that displays ":0" and ":0.0" are not completely equivalent. `frames-on-display-list` does call `get-device-terminal` internally, which complains that display ":0" was not found when `DISPLAY` was set to ":0.0". I worked around this problem by fixing `xcb:connect-to-socket`:
```lang=emacs-lisp
(defun xcb:connect-to-socket (&optional socket auth-info display)
...
;; use display in #'make-instance when given else fall back to old behaviour
```

and then fixing the call to it in `xcb:connect` to supply the value of `'display` from the current frame.
I am not sure if this is the right way to fix the problem, but the underlying wrong assumption seems to be that ":0.0" and ":0" are equivalent.

**Comment by ch11ng** [comment]
According to X(7), `:0` and `:0.0` are actually equivalent.  I think we should instead comparing display strings manually.

**Comment by spacefrogg** [comment]
Okay, I rephrase my statement: `get-device-terminal` does not treat `:0` and `:0.0` as equivalent. This means it, at least, does not accept `:0` as a display when it only knows about `:0.0`. (This is the exact case, I have tested, where it fails.) Maybe this should be filed as a bug against upstream?

**Comment by ch11ng** [comment]
I've pushed 851ed8c280cb9fe47f388773f3ee0ab90815fa99 and that should fix the problem correctly.

**Comment by yegortimoshenko** [comment]
@ch11ng Could you please cut a new release (0.15) with this fix? EXWM is currently broken on NixOS, and I had a hard time figuring out why: https://nixos.org/nixos/options.html#exwm

Or at least distribute this package on MELPA as well as on ELPA.

Such an amazing window manager, by the way. Thank you so much.

**Comment by tumashu** [comment]
guixsd need too :-),

**Comment by ch11ng** [comment]
Fine.
