### ISSUE TITLE
GUI windows sometimes go blank when changing screens

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#278]
I'm using emacs master branch checked out 26/05/2017 with exwm 0.14 and I've found a problem that happens **sometimes** where I'll be running google-chrome on my right screen and I change back to my centre screen and the google-chrome window on the right goes blank, except for the minibuffer. If I change to that screen and hit M-x the google-chrome GUI will become available again.

This has happened with Terminator GUI as well. I only happens with GUI applications not emacs buffers.

**Comment by ch11ng** [comment]
Does the blank here mean totally blank or the Emacs frame/window is still visible? Do you use the auto-hide minibuffer feature (by setting `exwm-workspace-minibuffer-position`)?

**Comment by map7** [comment]
The emacs frame is still visible.  Just the contents is black.  I don't auto hide the mini buffer

On 10 July 2017 2:11:02 AM AEST, Chris Feng <notifications@github.com> wrote:
>Does the blank here mean totally blank or the Emacs frame/window is
>still visible? Do you use the auto-hide minibuffer feature (by setting
>`exwm-workspace-minibuffer-position`)?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ch11ng/exwm/issues/278#issuecomment-313929230

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ch11ng** [comment]
I built Emacs from the latest source and did encounter an input focus issue.  Perhaps this is relevant and I'm still investigating on this.

**Comment by kinleyd** [comment]
I'm also experiencing this problem. Having set the following:
(setq exwm-workspace-show-all-buffers t)
(setq exwm-layout-show-all-buffers t)

Hitting C-x b allows me to select buffers across workspaces, except that for gui apps I have to hit M-x to complete the screen refresh.

**Comment by kinleyd** [comment]
As with the other issue I had raised: I just upgraded to Linux kernel 4.14.4-1 and now moving gui works across workspaces and screens works just fine - no M-x triggered refreshes required. exwm still at v. 0.16 - so something must have been fixed on the system side. Happy here. :)

**Comment by ch11ng** [comment]
I think this problem has been fixed in 71a39840b239a51eed7455877517ebe612892eff.  There was a compatibility issue with Emacs 26.

**Comment by agzam** [comment]
I am still experiencing this, strangely enough I **only** see it in Google-chrome. Firefox for example is fine.

**Comment by medranocalvo** [comment]
@map7, @kinleyd.  The fix by @ch11ng has been released for a long time.  I'm assuming your issue is resolved; please reopen if that's not the case.
