### ISSUE TITLE
When  exwm-workspace-minibuffer-postion is set to bottom active process in term steals focus from ivy

### ISSUE THREAD

**Issue by Sbozzolo** [ch11ng/exwm#359]
I reported this issue to the ivy project [here](https://github.com/abo-abo/swiper/issues/1429), but it turned out to be related do EXWM.
Essentially, when  `(setq exwm-workspace-minibuffer-position 'bottom)` is in my configuration files and I am running a process in a term-mode, `ivy` loses focus and it is impossible to move the cursor back to the minibuffer.

![gif](https://user-images.githubusercontent.com/9167485/35782325-5e306966-09b3-11e8-8bc4-06ccece3a223.gif)

**Comment by dakra** [comment]
I have maybe a related problem.

I have some global hydras to launch apps or toggle settings
and they work fine in Emacs buffers but in exwm buffers (mainly pidgin, firefox)
the hydra opens but then the focus is in the exwm buffer and no way to select
the minibuffer again.

It didn't bother me too much to investigate and report as I do almost everything in Emacs
buffers and thought it has to do with mouse over focus which apparently nobody
besides me uses.
But seeing your issue I think it could be the same problem.

**Comment by ch11ng** [comment]
Are you on Emacs 25? It seems to be a problem with pre-26 releases.

**Comment by Follpvosten** [comment]
I'm having a similar issue, but it's much worse - whenever I press tab to invoke completions in the minibuffer, the focus changes to the current workspace buffer (and all of the other problems mentioned here apply), while the completion buffer stays open. I can use the mouse to click options in the completion buffer, but that's the only way to make it work as intended. If I instead invoke `other-window` a couple of times, the completion window vanishes and the echo area shows "Quit". That basically makes EXWM unusable when the minibuffer/echo area is hidden. I hope Emacs 26 is gonna fix that (as i'm currently on 25).

**Comment by dakra** [comment]
I'm on Emacs 27/current git master with latest Exwm and the problem is still
there.

Easy way to reproduce is to install [hydra](https://github.com/abo-abo/hydra)
and then create a simple hydra like:

``` emacs-lisp
(defhydra hydra-exwmtest (:color blue)
  "exwm test"
  ("m" (lambda ()
         (interactive)
         (message "Doesn't work."))))
```

Then running `M-x hydra-exwmtest/body` shows the 'm' hint
and in a Emacs buffer you can press 'm' to show the message but in a X11 buffer
you can not.

**Comment by ch11ng** [comment]
The issues with ivy and minibuffer completion are fixed in Emacs 26 (I don't know which commit though).

The issue with hydra is actually different.  Hydra uses a transient keymap for reading the key.  It's fixed with fbdcd42b0a2aadb4f3e27cd2a75c863d2f67eb39.

**Comment by dakra** [comment]
> The issue with hydra is actually different. Hydra uses a transient keymap for reading the key. It's fixed with fbdcd42.

Thanks, I can confirm that my hydra issue is fixed in the latest version.

**Comment by medranocalvo** [comment]
@Sbozzolo, @Follpvosten, could you check whether the issue persists with latest EXWM and Emacs 26.1?

**Comment by Sbozzolo** [comment]
I cannot reproduce the problem with Emacs 26.1

**Comment by medranocalvo** [comment]
I can reproduce similar issues when setting `(setq exwm-workspace-minibuffer-postion 'bottom)` using my configuration. In my case, the focus alternates between the minibuffer and the workspace frame.

But I can't reproduce it when using a barebones configuration:

```bash
emacs -Q -L /path/to/exwm/ -L /path/to/xelb/ \
    --eval "(setq exwm-workspace-minibuffer-position 'bottom)" \
    --eval "(setq exwm-debug-on t)" \
    --eval "(require 'exwm)" \
    --eval "(exwm-init)";
```

and then:

<kbd>M-x package-initialize RET</kbd>
<kbd>M-x load-library RET ivy</kbd>
<kbd>C-x 3</kbd>
<kbd>M-x term</kbd>
... move pointer to other buffer...
<kbd>M-x ivy-switch-buffers RET</kbd>

Could you try reproducing it in such an environment?

**Comment by Sbozzolo** [comment]
This is what I did to reproduce the problem:
```
emacs -Q -L /path/to/exwm/ -L /path/to/xelb/ \
    --eval "(setq exwm-workspace-minibuffer-position 'bottom)" \
    --eval "(setq exwm-debug-on t)" \
    --eval "(require 'exwm)" \
    --eval "(exwm-init)";
```
and then:
`C-x 3`
`M-x term`
In term: `while 1; do echo "1" && sleep 2; done`
Move pointer in other buffer
`M-x`
When term writes, the point moves from the minibuffer to the second buffer.

It appears that `ivy` is not even required.

**Comment by medranocalvo** [comment]
Thank you for the recipe. The changes on #484 should fix the issue, please try them and report back.

**Comment by Sbozzolo** [comment]
I am using the latest commits for EXWM (+ PR) and XELB. I cannot reproduce the problem.

**Comment by Sbozzolo** [comment]
(With this I mean that it seems that the fix is effective, if the previous message wasn't clear)

**Comment by medranocalvo** [comment]
Happy to hear that.  Thank you for reporting back.
