### ISSUE TITLE
After exwm-workspace-switch, X window is read only if exwm-workspace-warp-cursor is set

### ISSUE THREAD

**Issue by WJCFerguson** [ch11ng/exwm#456]
This is a new issue (probably from between 4bb2d87 and 7e57503), When I switch to a workspace that already has an X window in focus, any un-simulated keypresses get "Buffer is read-only".  

(Edit: this problem occurs only if exwm-workspace-warp-cursor is set to true)

Many activities work around this and the window is writable again, like clicking in the window, moving to another window and back on that workspace, or toggling to another buffer in the same window, and back.

**Comment by medranocalvo** [comment]
Weird, this does not happen here, but sounds somewhat similar to #422 (the actions that fix it: clicking, etc...). Do you happen to use `focus-follows-mouse`? Could you try to reproduce #422 ?

The error message sounds like the EXWM buffer for an X window gets the keyboard focus instead of the X window itself.

It might help running EXWM in debug mode (`(setq exwm-debug-on t)` before requiring EXWM) and posting the messages here.

**Comment by WJCFerguson** [comment]
No focus-follows-mouse, but no doubt it could be something about my config.  Bisecting and investigating is awkward when it's your working environment :).  I'll check somethings out and report, but probably not today.

**Comment by WJCFerguson** [comment]
The above was reported when I was trying to use exwm as the window manager for XFCE (actually Xubuntu - the XFCE Ubuntu flavor) to try to get some of the benefits of a curated DE.

However, as of Ubuntu 18.04 and the latest exwm, the above problem emerged (along with other non-exwm-related problems - e.g. gnome-keyring-daemon and Chromium browser not playing nice - causing 30-60s wait for Chromium to start up).

I tried running without a DE - running startx, and still had the above problem, along with other issues I failed to resolve, like terrible looking fonts, and broken keyring daemon behavior.

I tried running under Gnome [`exwm-gnome`](https://github.com/WJCFerguson/exwm-gnome), and the above problem was still evident.

I'm now running under Gnome-Flashback [`exwm-gnome-flashback`](https://github.com/WJCFerguson/exwm-gnome-flashback), and the above problem has disappeared.

I'm assuming from all this that the problem is external to exwm, So I'll close it.

**Comment by WJCFerguson** [comment]
Meh, turns out it does still happen with Gnome-Flashback.  When I get the time I'll do a binary config search and see what makes it happen.

**Comment by WJCFerguson** [comment]
Discovery: it happens if `exwm-workspace-warp-cursor` is set to true.  I did so via the customize interface.

**Comment by ch11ng** [comment]
The implementation was problematic.  I've fixed it in 4d43e3119a2d0cb002d87340cd11c1d372ad126e.

**Comment by WJCFerguson** [comment]
Excellent thanks. I'm on vacation but look forward to checking it out.

**Comment by WJCFerguson** [comment]
Unfortunately, this doesn't fix it - and in fact my symptoms are the same whether the warp is achieved by `set-mouse-position` or by `xcb:WarpPointer`.  It only appears to happen when switching to a workspace that wasn't previously visible, i.e. to/from workspaces on the same monitor.  Issue #475 is a duplicate (sorry).

**Comment by ch11ng** [comment]
There seems to be a bug in XELB that prevents PropertyNotify events from being received in some cases.  I'm still investigating.

**Comment by ch11ng** [comment]
I've pushed a fixed (ch11ng/xelb@6656f4de9c75001b66c273f026c483ccf6599d57).  Please update XELB and try again.

**Comment by WJCFerguson** [comment]
Success - https://github.com/ch11ng/xelb/commit/6656f4de9c75001b66c273f026c483ccf6599d57 works!  Thank you.
