### ISSUE TITLE
Vlc broken with external monitor

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#62]
Vlc top menu (Media, Playback, Audio...) and rightclick in movie area are broken on external monitor. There is the click animation, but the related window does not appear. Other Vlc components such as Play/Stop button works. This only happens on external monitor, if Vlc is spawned/moved on/to LVDS1 it works as supposed. There is no error/message in ```*Messages*```.

My xrandr: https://gist.github.com/fm4d/4658026c03813bb3a2a2
Emacs version: 25.05 (same behaviour on 24.5)

**Comment by ch11ng** [comment]
Could you verify if 412d2a52bde98bb72fff9a848d5d28b6c5dff4c4 fixes this issue?

**Comment by fm4d** [comment]
Unfortunately it is still broken in the same way.

**Comment by ch11ng** [comment]
There're something I don't quite understand in your original post, namely 'click animation' and 'the related window'. What are they? And the VLC version I tested was 2.2.1, I don't know if it's different from yours.

**Comment by fm4d** [comment]
I have 2.2.1 also. Click animation means, that the elements of top menu react to mouse visualy on hoover and click, but the related window does not appear. Related window means the window that is supposed to appear, for example after clicking on the 'Media', the first menu element, related window is the window with 'Open File', 'Open Multiple Files', 'Open Directory' etc.

**Comment by ch11ng** [comment]
I see. I managed to reproduce this issue once, though not reliably. I'll try to figure out why.

**Comment by fm4d** [comment]
Thanks.

**Comment by ch11ng** [comment]
I think 4ad76b879d2f3807828de5345d5da4cac301415d should fix this issue. BTW, is there any news about #63?

**Comment by fm4d** [comment]
Well, nothing changed for me, still the same behaviour. About https://github.com/ch11ng/exwm/issues/63: I was off for a few days, so nothing new yet.

**Comment by ch11ng** [comment]
So could you paste the results of <kbd>M-&</kbd> `xwininfo -root -tree`, before and after you click the menu entry, with minimal GUI applications running?

**Comment by fm4d** [comment]
https://gist.github.com/fm4d/77dce5f87e7f8d5813e4

**Comment by ch11ng** [comment]
Which menu menu entry did you clicked? I can hardly see any difference between those outputs.

**Comment by fm4d** [comment]
I believe it was the 'Media' entry. 
The diff makes kinda sense, there is one more child in the output taken after clicking.

```
-     15 children:
-     0x100001f (has no name): ()  4547x1+0+0  +0+0
+     14 children:
+     0x1000005 (has no name): ()  1x1+0+0  +0+0
```

**Comment by ch11ng** [comment]
Sorry, I meant you should click a menu entry like 'Media -> Open files...' that opens a popup window (IIUC there's no problem showing the menu).

**Comment by fm4d** [comment]
Oh, I probably explained it totally wrong. It is the menu that does not appear. So for example after clicking on 'Media' nothing happens, the window with choices Media -> Open File, Media -> Open Multiple Files etc. does not appear.

**Comment by ch11ng** [comment]
So did you notice anything appears shortly on the other monitor (perhaps near the top-left corner)? And what would happen if you swap the screens or arrange them vertically? Does VLC in EXWM plays videos correctly (I mean the position and size the image region)?

**Comment by fm4d** [comment]
I tried all xrandr position settings (left-of/right-of/above/below), but no effect and I am sure that no window appears anywhere. Only way to make it work is moving VLC to LVDS1. VLC itself works correctly, no problems with position/size of the screen.

**Comment by ch11ng** [comment]
I really can't think of a reason, but perhaps the following random questions may help:
* Can you activate a menu with keyboard shortcut?
* Also, can you open a popup dialog with keyboard shortcut?
* Do other video players have the same problem?
* And what about other Qt applications?

**Comment by fm4d** [comment]
Yes, keyboard shortcuts work well. I tried some Qt applications like Calibre/Smplayer and they work well so.. Looks like I am the only one with this issue, so Ill probably just stick to different player and this issue can be closed.

**Comment by ch11ng** [comment]
What did you mean by saying 'keyboard shortcuts work well'? Did shortcuts such as <kbd>alt-m</kbd> bring up the corresponding menus?

**Comment by fm4d** [comment]
No, ```Alt-M``` and other 'menu' shortcuts are broken, only shortcuts spawning dialog windows like ```Ctrl-O``` work.

**Comment by ch11ng** [comment]
I'd suggest you try another window manager (especially one also use xrandr to configure multiscreen, for example i3) and see if this problem also happens there. Basically, menus in VLC are not managed by WMs (though WMs can affect the calculation of their positions). You might also check if there's something wrong in .xinitrc, .emacs, etc.

Anyway, I think we should keep this issue open for a considerable long time if this is an EXWM-only problem.

**Comment by fm4d** [comment]
Well, I tried stumpwm, which is very similar to i3/awesome and these lightweight tiing wms with same dual-monitor setup and everything worked well.

**Comment by ch11ng** [comment]
So there must be a problem in EXWM and perhaps it also affects other applications. I hope you'll bring us more news on this.

**Comment by ch11ng** [comment]
This is an old issue and I can not reproduce it.  I'm going to close it for now.  Feel free to reopen it if things are still not working.
